version: "3.8"

services:
  ui:
    build: ./app
    image: aspectodemo/ui
    stdin_open: true
    volumes:
      - "./app/src:/usr/src/app/src"
      - "./app/public:/usr/src/app/public"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "3002:3000"

  db:
    image: mongo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  user-service:
    build: "./services/user-service"
    image: aspectodemo/user-service
    volumes:
      - "./services/user-service/src:/usr/src/app/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8000:8080"
    environment:
      - NODE_ENV
      - ASPECTO_AUTH
      - ASPECTO_LIVE_FLOWS_URL
      - ASPECTO_GITHASH
      - ASPECTO_CI_REPORT
      - GITHUB_HEAD_REF
      - GITHUB_SHA
    depends_on:
      - db

  scraper-service:
    build: "./services/scraper-service"
    image: aspectodemo/scraper-service
    volumes:
      - "./services/scraper-service/src:/usr/src/app/src"
    environment:
      - NODE_ENV
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - ASPECTO_AUTH
      - ASPECTO_LIVE_FLOWS_URL
      - ASPECTO_GITHASH
      - GITHUB_HEAD_REF
      - GITHUB_SHA
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    ports:
      - "8001:8080"
    depends_on:
      - localstack

  wikipedia-processor:
    build: "./services/wikipedia-service"
    image: aspectodemo/wikipedia-service
    volumes:
      - "./services/wikipedia-service/src:/usr/src/app/src"
    environment:
      - NODE_ENV
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - MODE=PROCESSOR
      - ASPECTO_LIVE_FLOWS_URL
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
      - GITHUB_HEAD_REF
      - GITHUB_SHA
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    depends_on:
      - localstack
      - db

  wikipedia-server:
    build: "./services/wikipedia-service"
    image: aspectodemo/wikipedia-service
    volumes:
      - "./services/wikipedia-service/src:/usr/src/app/src"
    ports:
      - "8002:8080"
    environment:
      - NODE_ENV
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - MODE=SERVER
      - ASPECTO_LIVE_FLOWS_URL
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
      - GITHUB_HEAD_REF
      - GITHUB_SHA
    depends_on:
      - db
      - articles-cache

  articles-cache:
    image: redis
    ports:
      - 6379
    expose:
      - 6379

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localstack
