version: "3.8"

services:
  ui:
    build: ./app
    stdin_open: true
    volumes:
      - "./app/src:/usr/src/app/src"
      - "./app/public:/usr/src/app/public"
    ports:
      - "3033:3000"

  db:
    image: mongo

  user:
    build: "./services/user-service"
    volumes:
      - "./services/user-service/src:/usr/src/app/src"
    ports:
      - "8000:8080"
    environment:
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
    depends_on:
      - db

  # item:
  #   build: "./services/item-service"
  #   volumes:
  #     - "./services/item-service:/usr/src/app"
  #     - "/usr/src/app/node_modules"
  #   ports:
  #     - "8001:8080"
  #   environment:
  #     - ASPECTO_AUTH
  #     - ASPECTO_GITHASH
  #   depends_on:
  #     - redis
  #     - db
  #     - user

  # auction:
  #   build: "./services/auction-service"
  #   volumes:
  #     - "./services/auction-service:/usr/src/app"
  #     - "/usr/src/app/node_modules"
  #   ports:
  #     - "8002:8080"
  #   environment:
  #     - ASPECTO_AUTH
  #     - ASPECTO_GITHASH
  #     - AWS_ACCESS_KEY_ID=foobar
  #     - AWS_SECRET_ACCESS_KEY=foobar
  #     - AWS_DEFAULT_REGION=us-east-1 # default region for localstack
  #   depends_on:
  #     - redis
  #     - db
  #     - user
  #     - localstack

  scraper:
    build: "./services/scraper-service"
    volumes:
      - "./services/scraper-service/src:/usr/src/app/src"
    environment:
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    ports:
      - "8001:8080"
    depends_on:
      - localstack

  wikipedia-processor:
    build: "./services/wikipedia-service"
    volumes:
      - "./services/wikipedia-service/src:/usr/src/app/src"
    environment:
      - MODE=PROCESSOR
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    depends_on:
      - localstack
      - db

  wikipedia-server:
    build: "./services/wikipedia-service"
    volumes:
      - "./services/wikipedia-service/src:/usr/src/app/src"
    ports:
      - "8002:8080"
    environment:
      - MODE=SERVER
      - ASPECTO_AUTH
      - ASPECTO_GITHASH
    depends_on:
      - db
      - redis

  redis:
    image: redis
    ports:
      - 6379
    expose:
      - 6379

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localstack
