name: Test in CI
 
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  
  setup-system:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3002'
        env: 
          ASPECTO_CI_REPORT: 1
